# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
    ]
